sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_474ca4829f9e_key -iv $encrypted_474ca4829f9e_iv
  -in service-acount.json.enc -out service-acount.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project nomadic-flame-254800
- gcloud config set compute/zone us-central1-a
- gcloud container clusters get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t zefhon/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run zefhon/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
